### PR TITLE
2.1 oo install fixes

### PR DESCRIPTION
**Pull request by sosiouxme**
A few fixes to address recent issues.

### CODE REVIEW

**Comment by Miciah** [comment]
@sosiouxme, are any of these issues still relevant? Do we have Bugzilla reports for them?

**Comment by detiber** [comment]
@Miciah I would suspect that these are still relevant, there were some BZs assigned to me for some outstanding 2.x issues, including installations where /tmp is non-executable. Feel free to poach them, otherwise, I'll try to remember to go through and update them early next week.

**Comment by sosiouxme** [comment]
Yeah, I think the noexec /tmp and the httpd conf problem are still relevant, at least to anyone still trying to oo-install v2. If we said WONTFIX on the BZs and closed this I don't think it would have much impact at this point.

**Comment by sosiouxme** [comment]
OTOH this still merges cleanly...

**Pull request closed without merging**
