### PR TITLE
Bug 1168455

### PR DESCRIPTION
**Pull request by tiwillia**
Bugzilla link https://bugzilla.redhat.com/show_bug.cgi?id=1168455
Do not log passwords in plain text

### CODE REVIEW

**Comment by brenton** [comment]
For these you simply put the PR link in the bug and explain to QE how to test the change.  They know how to pull your code.

**Comment by brenton** [comment]
I don't remember exactly how to set up a test oo-install environment but we can do that next after they've verified the openshift.sh change.

**Comment by Miciah** [comment]
@tiwillia, please modify `enterprise/install-scripts/openshift.ks`, then run `make` from the `enterprise/install-scripts/` directory in order to generate the updated `enterprise/install-scripts/amazon/openshift-amz.sh` and `enterprise/install-scripts/generic/openshift.sh` files, and include all three in your commit and PR.  Otherwise your change will be lost the next time someone regenerates the `.sh` files, and confusion will ensue.

**Comment by Miciah** [comment]
Testing `oo-install` is cumbersome.  Basically you need to `export OO_INSTALL_KEEP_ASSETS=true`, run `oo-install`, quit `oo-install`, replace `openshift.sh` in the assets tarball that `oo-install` downloaded, and then rerun `oo-install`.

**Comment by tiwillia** [comment]
@Miciah, Thanks! All three should be updated now.

**Comment by brenton** [comment]
I'll plan on shipping the change in this PR to install.redhat.com's oo-install sometime today or tomorrow.

**Pull request merged**
